# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import snowflake_pb2 as snowflake__pb2


class SnowFlakeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_unique_url_id = channel.unary_unary(
                '/snowflake.SnowFlake/get_unique_url_id',
                request_serializer=snowflake__pb2.Request.SerializeToString,
                response_deserializer=snowflake__pb2.UniqueUrlID.FromString,
                )
        self.get_unique_user_id = channel.unary_unary(
                '/snowflake.SnowFlake/get_unique_user_id',
                request_serializer=snowflake__pb2.Request.SerializeToString,
                response_deserializer=snowflake__pb2.UniqueUserID.FromString,
                )


class SnowFlakeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_unique_url_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_unique_user_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SnowFlakeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_unique_url_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_unique_url_id,
                    request_deserializer=snowflake__pb2.Request.FromString,
                    response_serializer=snowflake__pb2.UniqueUrlID.SerializeToString,
            ),
            'get_unique_user_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_unique_user_id,
                    request_deserializer=snowflake__pb2.Request.FromString,
                    response_serializer=snowflake__pb2.UniqueUserID.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snowflake.SnowFlake', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SnowFlake(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_unique_url_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/snowflake.SnowFlake/get_unique_url_id',
            snowflake__pb2.Request.SerializeToString,
            snowflake__pb2.UniqueUrlID.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_unique_user_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/snowflake.SnowFlake/get_unique_user_id',
            snowflake__pb2.Request.SerializeToString,
            snowflake__pb2.UniqueUserID.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
