version: '3'
services:
  master:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_PASSWORD: postgres
    networks:
      - url-shortner_default
  shard1:
    image: postgres:12
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_PASSWORD: postgres
    networks:
      - url-shortner_default
  shard2:
    image: postgres:12
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_PASSWORD: postgres
    networks:
      - url-shortner_default
  web-server:
    image: url_shortener/web-server
    ports:
      - '8000:8000'
    networks:
      - url-shortner_default
    environment:
      DB_HOST: master
      SNOWFLAKE_HOST: snowflake
  snowflake:
    image: url_shortener/snowflake
    ports:
      - '5000:5000'
    networks:
      - url-shortner_default
networks:
  url-shortner_default:
    external: true
