# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snowflake.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='snowflake.proto',
  package='snowflake',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fsnowflake.proto\x12\tsnowflake\"\t\n\x07Request\"\x1c\n\x0bUniqueUrlID\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\x0cUniqueUserID\x12\r\n\x05value\x18\x01 \x01(\x03\x32\x8f\x01\n\tSnowFlake\x12?\n\x11get_unique_url_id\x12\x12.snowflake.Request\x1a\x16.snowflake.UniqueUrlID\x12\x41\n\x12get_unique_user_id\x12\x12.snowflake.Request\x1a\x17.snowflake.UniqueUserIDb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='snowflake.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=39,
)


_UNIQUEURLID = _descriptor.Descriptor(
  name='UniqueUrlID',
  full_name='snowflake.UniqueUrlID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='snowflake.UniqueUrlID.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=69,
)


_UNIQUEUSERID = _descriptor.Descriptor(
  name='UniqueUserID',
  full_name='snowflake.UniqueUserID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='snowflake.UniqueUserID.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['UniqueUrlID'] = _UNIQUEURLID
DESCRIPTOR.message_types_by_name['UniqueUserID'] = _UNIQUEUSERID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'snowflake_pb2'
  # @@protoc_insertion_point(class_scope:snowflake.Request)
  })
_sym_db.RegisterMessage(Request)

UniqueUrlID = _reflection.GeneratedProtocolMessageType('UniqueUrlID', (_message.Message,), {
  'DESCRIPTOR' : _UNIQUEURLID,
  '__module__' : 'snowflake_pb2'
  # @@protoc_insertion_point(class_scope:snowflake.UniqueUrlID)
  })
_sym_db.RegisterMessage(UniqueUrlID)

UniqueUserID = _reflection.GeneratedProtocolMessageType('UniqueUserID', (_message.Message,), {
  'DESCRIPTOR' : _UNIQUEUSERID,
  '__module__' : 'snowflake_pb2'
  # @@protoc_insertion_point(class_scope:snowflake.UniqueUserID)
  })
_sym_db.RegisterMessage(UniqueUserID)



_SNOWFLAKE = _descriptor.ServiceDescriptor(
  name='SnowFlake',
  full_name='snowflake.SnowFlake',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=103,
  serialized_end=246,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_unique_url_id',
    full_name='snowflake.SnowFlake.get_unique_url_id',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_UNIQUEURLID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_unique_user_id',
    full_name='snowflake.SnowFlake.get_unique_user_id',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_UNIQUEUSERID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SNOWFLAKE)

DESCRIPTOR.services_by_name['SnowFlake'] = _SNOWFLAKE

# @@protoc_insertion_point(module_scope)
